# Preprocessing

## Import library

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Import dataset

In [2]:
dataset = pd.read_csv('data.csv')
dataset.head()

Names  Age  ...                   Company  Churn
0        Aaron King   46  ...             Hernandez PLC      0
1       Aaron Meyer   45  ...    Steele, Bates and Lane      0
2        Aaron West   55  ...    Cruz, Russell and Boyd      0
3  Abigail Gonzalez   55  ...                Nelson PLC      0
4  Abigail Jennings   36  ...  Simpson, Byrd and Miller      0

[5 rows x 10 columns]

## Hapus variabel yang tidak digunakan

In [3]:
# Akan dihilangkan variabel "Names", "Onboard_date", "Location", dan "Company"
dataset = dataset.drop(labels=["Names", "Onboard_date", "Location", "Company"], axis=1)
dataset

Age  Total_Purchase  Account_Manager  Years  Num_Sites  Churn
0     46         7504.79                0   5.98          8      0
1     45         9598.03                0   5.00          7      0
2     55        10056.55                0   4.98          8      0
3     55         8243.28                0   3.54          6      0
4     36        12309.23                1   4.76          9      0
..   ...             ...              ...    ...        ...    ...
745   47         8291.93                0   4.47          7      0
746   53         8122.34                0   3.51          9      0
747   49         9000.36                0   4.13         11      0
748   28         8670.98                0   3.99          6      0
749   32         9885.12                1   6.92          9      1

[750 rows x 6 columns]

## Definisikan variabel

In [4]:
X = dataset.iloc[:, :5].values
X

array([[4.600000e+01, 7.504790e+03, 0.000000e+00, 5.980000e+00,
        8.000000e+00],
       [4.500000e+01, 9.598030e+03, 0.000000e+00, 5.000000e+00,
        7.000000e+00],
       [5.500000e+01, 1.005655e+04, 0.000000e+00, 4.980000e+00,
        8.000000e+00],
       ...,
       [4.900000e+01, 9.000360e+03, 0.000000e+00, 4.130000e+00,
        1.100000e+01],
       [2.800000e+01, 8.670980e+03, 0.000000e+00, 3.990000e+00,
        6.000000e+00],
       [3.200000e+01, 9.885120e+03, 1.000000e+00, 6.920000e+00,
        9.000000e+00]])

In [5]:
Y = dataset.iloc[:, 5].values
Y

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,

## Cek data

In [6]:
dataset.describe()

# 1. Diperoleh bahwa tidak ada data yang missing (lihat baris count)
# 2. Diperoleh bahwa kolom Total_Purchase mempunyai standar deviasi yang besar, sehingga nantinya akan dilakukan scaling (selain kolom yang dikodekan)

Age  Total_Purchase  ...   Num_Sites       Churn
count  750.000000      750.000000  ...  750.000000  750.000000
mean    41.850667    10055.878080  ...    8.649333    0.194667
std      6.141552     2350.437004  ...    1.808146    0.396208
min     22.000000     3263.000000  ...    3.000000    0.000000
25%     38.000000     8520.490000  ...    7.000000    0.000000
50%     41.000000    10045.870000  ...    9.000000    0.000000
75%     46.000000    11752.855000  ...   10.000000    0.000000
max     65.000000    18026.010000  ...   14.000000    1.000000

[8 rows x 6 columns]

In [7]:
print(dataset.groupby('Account_Manager').size()) # Variabel "Account_Manager" adalah data kategorik

Account_Manager
0    381
1    369
dtype: int64


## Bagi data menjadi training set dan test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [9]:
print(X_train)

[[4.000000e+01 7.642200e+03 0.000000e+00 5.040000e+00 9.000000e+00]
 [3.600000e+01 1.287970e+04 0.000000e+00 4.700000e+00 9.000000e+00]
 [4.400000e+01 6.517220e+03 0.000000e+00 4.550000e+00 1.200000e+01]
 ...
 [4.500000e+01 1.157584e+04 0.000000e+00 5.510000e+00 9.000000e+00]
 [4.500000e+01 9.721590e+03 0.000000e+00 3.430000e+00 9.000000e+00]
 [3.900000e+01 1.064367e+04 0.000000e+00 5.540000e+00 1.000000e+01]]


In [10]:
print(X_test)

[[3.600000e+01 1.228458e+04 1.000000e+00 5.700000e+00 9.000000e+00]
 [4.300000e+01 9.399920e+03 1.000000e+00 4.980000e+00 8.000000e+00]
 [4.100000e+01 1.442941e+04 1.000000e+00 5.510000e+00 1.100000e+01]
 [4.200000e+01 6.406380e+03 0.000000e+00 3.000000e+00 9.000000e+00]
 [3.400000e+01 1.046656e+04 0.000000e+00 5.340000e+00 7.000000e+00]
 [4.200000e+01 9.635870e+03 1.000000e+00 2.430000e+00 9.000000e+00]
 [4.400000e+01 1.058586e+04 0.000000e+00 5.540000e+00 8.000000e+00]
 [3.200000e+01 9.472720e+03 1.000000e+00 1.000000e+00 1.000000e+01]
 [3.900000e+01 9.353380e+03 0.000000e+00 4.060000e+00 7.000000e+00]
 [4.600000e+01 1.081459e+04 0.000000e+00 4.910000e+00 8.000000e+00]
 [4.000000e+01 8.083760e+03 0.000000e+00 4.760000e+00 7.000000e+00]
 [4.100000e+01 8.021050e+03 1.000000e+00 3.160000e+00 9.000000e+00]
 [3.400000e+01 9.401990e+03 1.000000e+00 8.250000e+00 9.000000e+00]
 [3.700000e+01 8.397410e+03 0.000000e+00 5.590000e+00 1.200000e+01]
 [4.600000e+01 9.988680e+03 1.000000e+00 5.44000

## Scaling

In [11]:
# Akan dilakukan scaling pada semua variabel X kecuali "Account_Manager"
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, :2] = sc.fit_transform(X_train[:, :2])
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, :2] = sc.fit_transform(X_test[:, :2])
X_test[:, 3:] = sc.fit_transform(X_test[:, 3:])

In [12]:
print(X_train)

[[-0.30749413 -1.01781533  0.         -0.22673952  0.17680023]
 [-0.95961374  1.19335965  0.         -0.49454387  0.17680023]
 [ 0.34462549 -1.49276094  0.         -0.61269285  1.83282904]
 ...
 [ 0.5076554   0.64289424  0.          0.14346061  0.17680023]
 [ 0.5076554  -0.13993559  0.         -1.49487188  0.17680023]
 [-0.47052403  0.24934942  0.          0.16709041  0.72880983]]


In [13]:
print(X_test)

[[-0.93454702  0.97009005  1.          0.35001933  0.24664505]
 [ 0.20421583 -0.29030342  1.         -0.18012072 -0.31202085]
 [-0.12114498  1.90722987  1.          0.21012126  1.36397686]
 [ 0.04153542 -1.5982698   0.         -1.63800586  0.24664505]
 [-1.25990784  0.17574321  0.          0.0849493  -0.87068675]
 [ 0.04153542 -0.18720987  1.         -2.05770007  0.24664505]
 [ 0.36689624  0.22786892  0.          0.23221043 -0.31202085]
 [-1.58526866 -0.25849495  1.         -3.11061712  0.80531096]
 [-0.4465058  -0.31063813  0.         -0.8575219  -0.87068675]
 [ 0.69225705  0.32780784  0.         -0.23166212 -0.31202085]
 [-0.28382539 -0.86537275  0.         -0.34210796 -0.87068675]
 [-0.12114498 -0.89277261  1.         -1.52019696  0.24664505]
 [-1.25990784 -0.28939898  1.          2.22759868  0.24664505]
 [-0.77186662 -0.72832977  0.          0.26902571  1.92264276]
 [ 0.69225705 -0.03305673  1.          0.15857987 -0.31202085]
 [ 1.83101991 -2.97170571  1.         -1.80735616  0.24

# Training dan Test

## Proses training

In [14]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Coba prediksi hasil dari X_test

In [15]:
Y_pred = classifier.predict(X_test)

In [16]:
print(Y_pred)

[0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 1 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0
 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1
 1 0 0]


## Bandingkan Y_pred dengan Y_test (Y_asli)

In [17]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test, Y_pred))

# Yang memprediksi benar/tepat adalah 149+19

[[149   6]
 [ 14  19]]


In [18]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_pred, Y_test))

# Skor akurasi model adalah sebesar 89%

0.8936170212765957


# Terapkan Model pada Data test.csv

In [19]:
dataset2 = pd.read_csv('test.csv')
dataset2

Names  ...                    Company
0         Anna Bryant  ...                Bennett Inc
1        Chris Sutton  ...                Collins Ltd
2       Connie Golden  ...               Brown-Wagner
3       Dennis Morgan  ...     Barry, Jordan and Hall
4        Erin Gilbert  ...    Ware, Williams and Hill
5        Jason Taylor  ...  Moore, Nichols and Miller
6   Kenneth Alexander  ...                 Torres Inc
7    Michael Williams  ...             Petty and Sons
8         Penny Perez  ...               Davis-Travis
9       Rachel Cherry  ...      Bishop, Tran and Pope
10       Robert Russo  ...              Hanna-Leonard
11     Robert Sanders  ...    White, Jones and Nelson
12        Sean Macias  ...              Jimenez Group
13       Seth Griffin  ...               Williams PLC
14        Tara Burton  ...                Reed-Fields
15       Yvette Perry  ...             Moore and Sons

[16 rows x 9 columns]

In [20]:
# Hilangkan variabel yang tidak digunakan
dataset2 = dataset2.drop(labels=["Onboard_date", "Location", "Company"], axis=1) # Variabel "Names" tidak dihilangkan agar dapat dipanggil nantinya
dataset2.head()

Names  Age  Total_Purchase  Account_Manager  Years  Num_Sites
0    Anna Bryant   39         8801.86                1   4.43         10
1   Chris Sutton   37        10314.67                1   5.86          8
2  Connie Golden   39        10268.87                1   3.68          6
3  Dennis Morgan   43         8042.76                0   4.95          8
4   Erin Gilbert   35        12357.31                0   5.03         10

In [21]:
prediksi_X = dataset2.iloc[:, 1:].values
print(prediksi_X)

[[3.900000e+01 8.801860e+03 1.000000e+00 4.430000e+00 1.000000e+01]
 [3.700000e+01 1.031467e+04 1.000000e+00 5.860000e+00 8.000000e+00]
 [3.900000e+01 1.026887e+04 1.000000e+00 3.680000e+00 6.000000e+00]
 [4.300000e+01 8.042760e+03 0.000000e+00 4.950000e+00 8.000000e+00]
 [3.500000e+01 1.235731e+04 0.000000e+00 5.030000e+00 1.000000e+01]
 [4.600000e+01 5.570450e+03 0.000000e+00 2.230000e+00 7.000000e+00]
 [3.000000e+01 8.403780e+03 1.000000e+00 4.130000e+00 7.000000e+00]
 [3.500000e+01 1.557126e+04 0.000000e+00 6.450000e+00 9.000000e+00]
 [4.400000e+01 1.030915e+04 1.000000e+00 6.350000e+00 9.000000e+00]
 [5.200000e+01 9.782830e+03 0.000000e+00 3.960000e+00 7.000000e+00]
 [5.800000e+01 9.703930e+03 0.000000e+00 5.160000e+00 1.100000e+01]
 [2.900000e+01 9.378240e+03 0.000000e+00 4.930000e+00 8.000000e+00]
 [4.700000e+01 1.130610e+04 0.000000e+00 6.010000e+00 7.000000e+00]
 [4.400000e+01 1.232803e+04 1.000000e+00 4.600000e+00 9.000000e+00]
 [4.900000e+01 1.117708e+04 0.000000e+00 4.44000

In [22]:
# Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
prediksi_X[:, :2] = sc.fit_transform(prediksi_X[:, :2])
prediksi_X[:, 3:] = sc.fit_transform(prediksi_X[:, 3:])
print(prediksi_X)

[[-0.36484697 -0.60684942  1.         -0.31445947  0.70014004]
 [-0.63019022  0.09104304  1.          1.03795269 -0.42008403]
 [-0.36484697  0.06991449  1.         -1.02376655 -1.54030809]
 [ 0.16583953 -0.95703891  0.          0.17732677 -0.42008403]
 [-0.89553347  1.03335771  0.          0.25298619  0.70014004]
 [ 0.56385441 -2.09756978  0.         -2.39509356 -0.98019606]
 [-1.5588916  -0.79049246  1.         -0.5981823  -0.98019606]
 [-0.89553347  2.51602339  0.          1.59594092  0.14002801]
 [ 0.29851116  0.08849654  1.          1.50136664  0.14002801]
 [ 1.35988416 -0.15430643  0.         -0.75895857 -0.98019606]
 [ 2.15591391 -0.19070473  0.          0.37593275  1.26025208]
 [-1.69156322 -0.34095267  0.          0.15841191 -0.42008403]
 [ 0.69652603  0.54841146  0.          1.1798141  -0.98019606]
 [ 0.29851116  1.0198502   1.         -0.1536832   0.14002801]
 [ 0.96186928  0.4888917   0.         -0.30500204  1.82036411]
 [-0.09950372 -0.71807414  1.         -0.73058629  1.82

In [23]:
prediksi_Y = classifier.predict(prediksi_X)
print(prediksi_Y)

[0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1]


In [29]:
nama = dataset2["Names"].values
print(nama)

['Anna Bryant' 'Chris Sutton' 'Connie Golden' 'Dennis Morgan'
 'Erin Gilbert' 'Jason Taylor' 'Kenneth Alexander' 'Michael Williams'
 'Penny Perez' 'Rachel Cherry' 'Robert Russo' 'Robert Sanders'
 'Sean Macias' 'Seth Griffin' 'Tara Burton' 'Yvette Perry']


In [34]:
print(np.concatenate((nama.reshape(len(nama), 1), prediksi_Y.reshape(len(prediksi_Y), 1)), 1))

[['Anna Bryant' 0]
 ['Chris Sutton' 0]
 ['Connie Golden' 0]
 ['Dennis Morgan' 0]
 ['Erin Gilbert' 0]
 ['Jason Taylor' 0]
 ['Kenneth Alexander' 0]
 ['Michael Williams' 0]
 ['Penny Perez' 0]
 ['Rachel Cherry' 0]
 ['Robert Russo' 1]
 ['Robert Sanders' 0]
 ['Sean Macias' 0]
 ['Seth Griffin' 0]
 ['Tara Burton' 1]
 ['Yvette Perry' 1]]
